### ISSUE TITLE
consistency?

### ISSUE THREAD

**Issue by tgs** [tgs/nptime#2]
It's odd for the units to change when you're just doing addition and subtraction.  Should I unify nptime and timedelta into one "timecircle" class or something?  That unifies "time since midnight" with "time since ____"?

Or should I just change the return value of **sub**:

nptime - nptime = timedelta
nptime - timedelta = nptime

What happens when you do nptime + timedelta - timedelta? (n+t)-t -> (n)-t -> n, that's right

(n + t - t) - n -> ((n + t) - t) - n -> ((n) - t) - n -> (n) - n -> t

Which is more useful?  One unified hours:minutes:seconds type, or something that keeps timedelta separate?

**Comment by dolonnen** [comment]
Hi, I discovered this module just yesterday. It's amazing to find a time object with the possibility of arithmetric. Thank you for that.

But i stumbled on nptime - timedelta.

Why return this a timedelta and nptime + timedelta returns a nptime? If I want to subtract some time from a moment, I want to go to the past like I want go to the future if I add some time to a moment.

Sure, nptime.from_timedelta(nptime - timedelta) works. But its not consistence and looks ugly.

**Comment by tgs** [comment]
It's true, it still makes no sense, 7 years later.  Hmm.

I wonderrrrr if anyone out there is relying on that weird behavior.  It's too bad it's a magic method, there's no way to have two versions of it.  The fix is easy, though...  I've pushed it to `master`.  Could you try it and confirm it's what you want?

**Comment by dolonnen** [comment]
I played with it and it works perfectly. Many thanks for that. Its better than my solution, i've make yesterday:
```
class mynptime(nptime):
    def __sub__(self, other):
        result = super().__sub__(other)
        if isinstance(result, timedelta):
            return super().from_timedelta(result)
        else:
            return result
```
:-D

**Comment by tgs** [comment]
OK, I've released nptime 1.0 with this change :)

**Comment by dolonnen** [comment]
Many Thanks. On http://tgs.github.io/nptime/ there is still the wrong information

**Comment by tgs** [comment]
Ah! Thanks for noticing. Fixed.
